"""Spectral pristine-upstream parity tests.

Reads the fixture generated by `verification/upstream/oracle_spectral.cpp`,
replays the recorded inputs through the public Python spectral API, and compares
only numerical outputs against pristine qm-dsp outputs.
"""

import numpy as np

from pyqmdsp import spectral

# Data adapters ---------------------------------------------------------------


def _array(values):
    return np.asarray(values, dtype=np.float64)


def _pair(real, imag):
    return {"real": np.asarray(real), "imag": np.asarray(imag)}


def _triple(values):
    mag, phase, unwrapped = values
    return {"mag": np.asarray(mag), "phase": np.asarray(phase), "unwrapped": np.asarray(unwrapped)}


# Domain replays --------------------------------------------------------------


def _actual_fft(inputs):
    fft = spectral.FFT(len(inputs["real"]))
    real, imag = fft.process(inputs["real"], inputs["imag"])
    inv_real, inv_imag = fft.process(real, imag, inverse=True)
    ro_real, ro_imag = fft.process(inputs["real"])
    return {
        "forward": _pair(real, imag),
        "inverse": _pair(inv_real, inv_imag),
        "real_only_forward": _pair(ro_real, ro_imag),
    }


def _actual_real_fft(inputs):
    fft = spectral.RealFFT(len(inputs))
    real, imag = fft.forward(inputs)
    return {
        "forward": _pair(real, imag),
        "magnitude": fft.forward_magnitude(inputs),
        "inverse": fft.inverse(real[: fft.bins], imag[: fft.bins]),
    }


def _actual_dct(inputs):
    dct = spectral.DCT(len(inputs))
    forward = dct.forward(inputs)
    forward_unitary = dct.forward(inputs, unitary=True)
    return {
        "forward": forward,
        "forward_unitary": forward_unitary,
        "inverse": dct.inverse(forward),
        "inverse_unitary": dct.inverse(forward_unitary, unitary=True),
    }


def _actual_constant_q(inputs):
    cq = spectral.ConstantQ(
        22050.0,
        440.0 * 2 ** ((40.0 - 69.0) / 12.0),
        440.0 * 2 ** ((88.0 - 69.0) / 12.0),
        bins_per_octave=24,
        threshold=0.004,
    )
    real, imag = cq.process_frequency(inputs["fft_real"], inputs["fft_imag"])
    return {
        "bins": cq.bins,
        "fft_length": cq.fft_length,
        "hop": cq.hop,
        "q": cq.q,
        "process_frequency": _pair(real, imag),
    }


def _chromagram(sample_rate, min_pitch, max_pitch, *, bins=24, normalise="none"):
    return spectral.Chromagram(
        sample_rate,
        440.0 * 2 ** ((min_pitch - 69.0) / 12.0),
        440.0 * 2 ** ((max_pitch - 69.0) / 12.0),
        bins_per_octave=bins,
        threshold=0.004,
        normalise=normalise,
    )


def _actual_chromagram(inputs):
    chroma_none = _chromagram(22050.0, 36.0, 84.0, normalise="none")
    chroma_sum = _chromagram(22050.0, 36.0, 84.0, normalise="unit_sum")
    chroma_max = _chromagram(22050.0, 36.0, 84.0, normalise="unit_max")
    return {
        "bins": chroma_none.bins,
        "cq_bins": chroma_none.cq_bins,
        "frame_size": chroma_none.frame_size,
        "hop_size": chroma_none.hop_size,
        "time_none": chroma_none.process_time(inputs["time"]),
        "frequency_none": chroma_none.process_frequency(inputs["fft_real"], inputs["fft_imag"]),
        "time_unit_sum": chroma_sum.process_time(inputs["time"]),
        "time_unit_max": chroma_max.process_time(inputs["time"]),
        "unity_normalise": chroma_none.unity_normalise(inputs["unity_values"]),
        "kabs": chroma_none.kabs(3.5, -4.25),
    }


def _actual_mfcc(inputs):
    mfcc = spectral.MFCC(
        16000,
        fft_size=128,
        n_coefficients=7,
        log_power=2.0,
        want_c0=False,
        window="blackman",
    )
    return {
        "fft_length": mfcc.fft_length,
        "output_size": mfcc.output_size,
        "time": mfcc.process_time(inputs["frame"]),
        "frequency": mfcc.process_frequency(inputs["fft_real"], inputs["fft_imag"]),
    }


def _actual_mfcc_default(inputs):
    mfcc = spectral.MFCC(16000)
    return {
        "fft_length": mfcc.fft_length,
        "output_size": mfcc.output_size,
        "time": mfcc.process_time(inputs["frame"]),
        "frequency": mfcc.process_frequency(inputs["fft_real"], inputs["fft_imag"]),
    }


def _actual_phase_vocoder(inputs):
    pv = spectral.PhaseVocoder(16, 4)
    time = {}
    time["frame0"] = _triple(pv.process_time(inputs["frame0"]))
    time["frame1"] = _triple(pv.process_time(inputs["frame1"]))
    pv.reset()
    time["after_reset"] = _triple(pv.process_time(inputs["frame2"]))
    return {
        "size": pv.size,
        "hop": pv.hop,
        "bins": pv.bins,
        "time": time,
        "frequency": _triple(pv.process_frequency(inputs["freq_real"], inputs["freq_imag"])),
    }


def _actual_key(inputs):
    key = spectral.KeyMode(
        22050.0,
        tuning_frequency=442.0,
        hpcp_average=0.2,
        median_average=0.2,
        frame_overlap_factor=2,
        decimation_factor=4,
    )
    stream = _array(inputs)
    keys = []
    for offset in range(0, stream.size - key.block_size + 1, key.hop_size):
        keys.append(key.process(stream[offset : offset + key.block_size]))
    return {
        "block_size": key.block_size,
        "hop_size": key.hop_size,
        "keys": keys,
        "strengths": key.key_strengths(),
    }


def _actual_tonal(inputs):
    estimator = spectral.TonalEstimator()
    return {
        "transform": estimator.transform_chroma(inputs["chroma"]),
        "normalize_chroma": spectral.normalize_chroma(inputs["normalize_chroma"]),
        "magnitude": spectral.tonal_magnitude(inputs["magnitude_tcs"]),
    }


def _actual_tcsgram(inputs):
    gram = spectral.TCSGram(12.5, reserve=len(inputs))
    for row in inputs:
        gram.add(row)
    before_clear = {
        "size": gram.size,
        "duration": gram.duration,
        "time_2": gram.time_at(2),
        "vector_1": gram.vector_at(1),
        "matrix": gram.matrix(),
    }
    gram.set_frame_duration_ms(25.0)
    gram.add([0.9, -0.8, 0.7, -0.6, 0.5, -0.4])
    after_setter = {"size": gram.size, "duration": gram.duration, "time_4": gram.time_at(4)}
    gram.clear()
    after_clear = {"size": gram.size, "duration": gram.duration}
    return {
        "before_clear": before_clear,
        "after_setter": after_setter,
        "after_clear": after_clear,
    }


def _actual_change_detection(inputs):
    matrix = _array(inputs)
    gram0 = spectral.TCSGram(10.0, reserve=len(inputs))
    gram2 = spectral.TCSGram(10.0, reserve=len(inputs))
    for row in inputs:
        gram0.add(row)
        gram2.add(row)
    width0 = spectral.ChangeDetection(0)
    width2 = spectral.ChangeDetection(2)
    return {
        "width_0_tcsgram": width0.process_tcsgram(gram0),
        "width_2_tcsgram": width2.process_tcsgram(gram2),
        "width_0_matrix": spectral.ChangeDetection(0).process_matrix(matrix, frame_duration_ms=10.0),
        "width_2_matrix": spectral.ChangeDetection(2).process_matrix(matrix, frame_duration_ms=10.0),
    }


def _actual_wavelets(expected_names):
    names = spectral.wavelet_names()
    actual_names = {str(i): name for i, name in enumerate(names)}
    filters = {}
    for key, name in expected_names.items():
        selector = int(key) if int(key) % 2 == 0 else name
        low, high = spectral.wavelet_filters(selector)
        filters[key] = {"name": name, "low": low, "high": high}
    return actual_names, filters


def _actual_convenience(inputs):
    fft_real, fft_imag = spectral.fft(inputs["fft"]["real"], inputs["fft"]["imag"])
    real_fft_real, real_fft_imag = spectral.real_fft(inputs["real_fft"])
    dct_unitary = spectral.dct(inputs["dct"], unitary=True)
    idct_unitary = spectral.idct(dct_unitary, unitary=True)
    tonal = spectral.tonal_transform(inputs["tonal"]["chroma"])
    return {
        "fft": _pair(fft_real, fft_imag),
        "real_fft": _pair(real_fft_real, real_fft_imag),
        "dct": dct_unitary,
        "idct": idct_unitary,
        "tonal_transform": tonal,
    }


# Full parity -----------------------------------------------------------------


def test_spectral_upstream_parity(reference, assert_matches):
    expected = reference("spectral")
    inputs = expected["inputs"]
    expected_outputs = expected["outputs"]
    wavelet_names, wavelet_filters = _actual_wavelets(expected_outputs["wavelet_names"])
    actual_outputs = {
        "fft": _actual_fft(inputs["fft"]),
        "real_fft": _actual_real_fft(inputs["real_fft"]),
        "dct": _actual_dct(inputs["dct"]),
        "constant_q": _actual_constant_q(inputs["constant_q"]),
        "chromagram": _actual_chromagram(inputs["chromagram"]),
        "mfcc": _actual_mfcc(inputs["mfcc"]),
        "mfcc_default": _actual_mfcc_default(inputs["mfcc_default"]),
        "phase_vocoder": _actual_phase_vocoder(inputs["phase_vocoder"]),
        "key": _actual_key(inputs["key"]),
        "tonal": _actual_tonal(inputs["tonal"]),
        "tcsgram": _actual_tcsgram(inputs["tcsgram"]),
        "change_detection": _actual_change_detection(inputs["change_detection"]),
        "wavelet_names": wavelet_names,
        "wavelet_filters": wavelet_filters,
        "convenience": _actual_convenience(inputs),
    }
    assert_matches(actual_outputs, expected_outputs)
